config:
    version: 3

    n_classes: 2
    depth: 4
    base_filters: 64
    skips: True
    bndry_dropout: True
    bndry_dropout_p: 2.0e-1

    # The number of in channels is calculated using the options below
    tb_channels: [0, 1, 2, 3, 4]
    use_land_mask: False
    use_dem: True
    use_latitude: False
    use_day_of_year: False
    use_solar: False
    use_snow: False
    use_prior_day: True

    normalize: False
    # This must match one of the region codes in scripts/transforms.py
    region: n45
    train_start_year: 2005
    train_end_year: 2014
    test_start_year: 2016
    test_end_year: 2016

    epochs: 1100
    batch_size: 28
    drop_last: False
    learning_rate: 1.0e-4
    lr_milestones: [350, 600, 750, 850, 950, 1000, 1050]
    lr_step_gamma: 0.5

    l2_reg_weight: 1.0e-2
    main_loss_weight: 1.0e-0
    aws_bce_weight: 5.0e+2
    lv_reg_weight: 5.0e-2
    aws_use_valid_mask: False
    val_use_valid_mask: False

    do_val_plots: False
    do_pred_plots: False

    runs_dir: "../data/runs"
    db_path: "../data/dbs/wmo_gsod.db"
    land_mask_path: "../data/masks/ft_esdr_land_mask_n45.npy"
    dem_data_path: "../data/z/dem-n45.npy"
    lon_grid_path: "../data/coords/lon_n45.npy"
    lat_grid_path: "../data/coords/lat_n45.npy"

    train_aws_data_path: "../data/cleaned/aws_data-AM-2005-2014-n45.pkl"
    train_date_map_path: "../data/cleaned/date_map-2005-2014-n45.csv"
    train_tb_data_path: "../data/cleaned/tb-D-2005-2014-n45.npy"
    train_era5_ft_data_path: "../data/cleaned/era5-ft-am-2005-2014-n45.npy"
    train_solar_data_path: "../data/cleaned/solar_rad-AM-2005-2014-n45.npy"
    train_snow_data_path: "../data/cleaned/snow_cover-2005-2014-n45.npy"

    test_aws_data_path: "../data/cleaned/aws_data-AM-2016-n45.pkl"
    test_date_map_path: "../data/cleaned/date_map-2016-n45.csv"
    test_tb_data_path: "../data/cleaned/tb-D-2016-n45.npy"
    test_era5_ft_data_path: "../data/cleaned/era5-ft-am-2016-n45.npy"
    test_solar_data_path: "../data/cleaned/solar_rad-AM-2016-n45.npy"
    test_snow_data_path: "../data/cleaned/snow_cover-2016-n45.npy"
